#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-mapr-hadoop
Version  : 1
Release  : 1
URL      : http://repository.mapr.com/maven/org/apache/hadoop/hadoop-common/2.7.0-mapr-1703/hadoop-common-2.7.0-mapr-1703.jar
Source0  : http://repository.mapr.com/maven/org/apache/hadoop/hadoop-common/2.7.0-mapr-1703/hadoop-common-2.7.0-mapr-1703.jar
Source1  : http://repository.mapr.com/maven/org/apache/hadoop/hadoop-annotations/2.7.0-mapr-1703/hadoop-annotations-2.7.0-mapr-1703.jar
Source2  : http://repository.mapr.com/maven/org/apache/hadoop/hadoop-annotations/2.7.0-mapr-1703/hadoop-annotations-2.7.0-mapr-1703.pom
Source3  : http://repository.mapr.com/maven/org/apache/hadoop/hadoop-auth/2.7.0-mapr-1703/hadoop-auth-2.7.0-mapr-1703.jar
Source4  : http://repository.mapr.com/maven/org/apache/hadoop/hadoop-auth/2.7.0-mapr-1703/hadoop-auth-2.7.0-mapr-1703.pom
Source5  : http://repository.mapr.com/maven/org/apache/hadoop/hadoop-common/2.7.0-mapr-1703/hadoop-common-2.7.0-mapr-1703.pom
Source6  : http://repository.mapr.com/maven/org/apache/hadoop/hadoop-main/2.7.0-mapr-1703/hadoop-main-2.7.0-mapr-1703.pom
Source7  : http://repository.mapr.com/maven/org/apache/hadoop/hadoop-project-dist/2.7.0-mapr-1703/hadoop-project-dist-2.7.0-mapr-1703.pom
Source8  : http://repository.mapr.com/maven/org/apache/hadoop/hadoop-project/2.7.0-mapr-1703/hadoop-project-2.7.0-mapr-1703.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-mapr-hadoop-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-mapr-hadoop package.
Group: Data

%description data
data components for the mvn-mapr-hadoop package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-common/2.7.0-mapr-1703
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-common/2.7.0-mapr-1703/hadoop-common-2.7.0-mapr-1703.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-annotations/2.7.0-mapr-1703
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-annotations/2.7.0-mapr-1703/hadoop-annotations-2.7.0-mapr-1703.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-annotations/2.7.0-mapr-1703
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-annotations/2.7.0-mapr-1703/hadoop-annotations-2.7.0-mapr-1703.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-auth/2.7.0-mapr-1703
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-auth/2.7.0-mapr-1703/hadoop-auth-2.7.0-mapr-1703.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-auth/2.7.0-mapr-1703
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-auth/2.7.0-mapr-1703/hadoop-auth-2.7.0-mapr-1703.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-common/2.7.0-mapr-1703
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-common/2.7.0-mapr-1703/hadoop-common-2.7.0-mapr-1703.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-main/2.7.0-mapr-1703
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-main/2.7.0-mapr-1703/hadoop-main-2.7.0-mapr-1703.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-project-dist/2.7.0-mapr-1703
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-project-dist/2.7.0-mapr-1703/hadoop-project-dist-2.7.0-mapr-1703.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-project/2.7.0-mapr-1703
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-project/2.7.0-mapr-1703/hadoop-project-2.7.0-mapr-1703.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-annotations/2.7.0-mapr-1703/hadoop-annotations-2.7.0-mapr-1703.jar
/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-annotations/2.7.0-mapr-1703/hadoop-annotations-2.7.0-mapr-1703.pom
/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-auth/2.7.0-mapr-1703/hadoop-auth-2.7.0-mapr-1703.jar
/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-auth/2.7.0-mapr-1703/hadoop-auth-2.7.0-mapr-1703.pom
/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-common/2.7.0-mapr-1703/hadoop-common-2.7.0-mapr-1703.jar
/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-common/2.7.0-mapr-1703/hadoop-common-2.7.0-mapr-1703.pom
/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-main/2.7.0-mapr-1703/hadoop-main-2.7.0-mapr-1703.pom
/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-project-dist/2.7.0-mapr-1703/hadoop-project-dist-2.7.0-mapr-1703.pom
/usr/share/java/.m2/repository/org/apache/hadoop/hadoop-project/2.7.0-mapr-1703/hadoop-project-2.7.0-mapr-1703.pom
